volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/config/prometheus.yaml"
      - "--storage.tsdb.retention.time=365d"
      - "--storage.tsdb.retention.size=2GB"
    ports:
      - "9090:9090"
    volumes:
      - ./config:/config
      - ./prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - metrics
      - watchtower_metrics
      - dsmr5_metrics
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.home`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # ports:
      # - "8080:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - metrics
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.home`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    #ports:
    #  - "9100:9100"
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    networks:
      - metrics

  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64:v0.52.1
    container_name: cadvisor
    privileged: true
    command:
      - "--port=9092"
    #ports:
    #  - "9092:9092"
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - DOCKER_API_VERSION=1.52
    networks:
      - metrics

networks:
  metrics:
  traefik_web:
    external: true
  watchtower_metrics:
    external: true
  dsmr5_metrics:
    external: true
